// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp-v9XBvdXY6WKwIIz6hE1KSN4TTmNb-g',
    appId: '1:194268734639:web:42e92dbd2790c36b91e05a',
    messagingSenderId: '194268734639',
    projectId: 'fir-flutter-codelab-35ec9',
    authDomain: 'fir-flutter-codelab-35ec9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-35ec9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrdh9o5nbFJhpPbiZmHJYh-iiq68uBwzc',
    appId: '1:194268734639:android:e10c94e6c841b3ad91e05a',
    messagingSenderId: '194268734639',
    projectId: 'fir-flutter-codelab-35ec9',
    storageBucket: 'fir-flutter-codelab-35ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpPNKqRcHNLbKbLfP1rQVYVRg0FPDctPk',
    appId: '1:194268734639:ios:44ddffd84caf3b6491e05a',
    messagingSenderId: '194268734639',
    projectId: 'fir-flutter-codelab-35ec9',
    storageBucket: 'fir-flutter-codelab-35ec9.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpPNKqRcHNLbKbLfP1rQVYVRg0FPDctPk',
    appId: '1:194268734639:ios:22cd13bd2a58d64591e05a',
    messagingSenderId: '194268734639',
    projectId: 'fir-flutter-codelab-35ec9',
    storageBucket: 'fir-flutter-codelab-35ec9.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
